# Puppetlabs Modules
####################
mod 'puppetlabs/apt',         :latest
mod 'puppetlabs/concat',      :latest
mod 'puppetlabs/git',         :latest
mod 'puppetlabs/inifile',     :latest
mod 'puppetlabs/ntp',         :latest
mod 'puppetlabs/stdlib',      :latest
mod 'puppetlabs/vcsrepo',     :latest

# Contrib modules
#################
mod 'saz/timezone'
mod 'camptocamp/systemd'